.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "ORM64" "1" "January 1980" ""
.SH "NAME"
\fBorm64\fR \- Fantasy "Operating" System
.SH "SYNOPSIS"
orm64
.SH "DESCRIPTION"
Fantasy operating system or what I call it now: an API layer for creating Software with Lua\.
.SH "EXAMPLES"
$ orm64
.P
Starts Orm64
