#+TITLE: orm64

A simple, lua-based, fantasy operating system.

It's kinda like those fantasy game consoles, except its meant to be an enitre OS.

* Why?

Because I had enough of making FizzBuzz projects!

* Dependencies

In order to use this program you will need the dependencies listed below:

- Unix based system, (MacOS and Linux tested, unsure about BSDs)
- [[https://luajit.org]]
- [[https://raylib.com]]
- [[https://invisible-island.net/ncurses]]
- pkg-config
- libedit
- git

* Building

Building requires Meson

Make a directory called *bin*

Inside of it run *meson ..* and then run *meson compile*

* TODO Roadmap
- [X] Lua REPL
- [X] Application, and Libraries
- [X] Package manager (To install apps and libraries)
- [-] An API with a bunch of modules to create lots of things
  - [X] Graphics and Multimedia layer
  - [ ] Terminal Manipulation library
  - [ ] Networking and HTTP library
  - [X] User interaction library
- [ ] File system
- [ ] Plugin system
- [X] User system
- [X] C/C++ Library for interacting with Orm64

* History

I first wrote this in [[https://rust-lang.org]].

But of course I had issues with the borrow checker and the [[https://github.com/mlua-rs/mlua]] API

So I decided to rewrite Orm64 in C, since C lets you do just about anything in any way you want.

I found pointers and memory allocation (Thanks to my experience in Rust) easy and I ended up really liking C. 
I guess from now on I will write most of my projects in C!
