#+TITLE: orm64

A simple, lua-based, fantasy operating system.

It's kinda like those fantasy game consoles, except its meant to be an enitre OS.


* Roadmap

- [X] Lua REPL
- [X] Application, and Libraries
- [X] Package manager
- [-] An API with a bunch of modules to create lots of things
  - [X] Graphics and Multimedia layer
  - [ ] Networking and HTTP library
  - [X] User interaction library
- [ ] File system
- [X] User system
- [X] C/C++ Library for interacting with Orm64
- [ ] Advanced Configuration
  
* History

I first wrote this in [[https://rust-lang.org]].

But of course I had issues with the borrow checker and the [[https://github.com/mlua-rs/mlua]] API

So I decided to rewrite Orm64 in C, since C lets you do just about anything in any way you want.

I found pointers and memory allocation (Thanks to my experience in Rust) easy and I ended up really liking C. 
I guess from now on I will write most of my projects in C!

I rewrote this in C++ a month after the C rewrite for some nice features like the *new* and *delete* keywords and lambdas.

* Other stuff

This project *probably* has a bunch of crappy code.
But don't blame me it's my first big C/C++ project in 2 years.
