.SH NAME
.IP
.EX
orm64
.EE
.SH SYNOPSIS
.IP
.EX
orm64 ...
.EE
.SH DESCRIPTION
.IP
.EX
Fantasy operating system or what I call it now: an API layer for creating Software with Lua.

help \- Lists commands
script \- Run Lua code
.EE
.SH EXAMPLES
.IP
.EX
$ orm64 
Simply starts the Orm64 shell.

$ orm64 help
Lists commands avaliable for Orm64

$ orm64 script \[dq]print(32)\[dq]
Prints 32 using Lua
.EE
